version: "3.1"
services:
    db:
      image: mysql:5.6
      container_name: student-mysql
      working_dir: /application
      volumes:
        - ./data:/docker-entrypoint-initdb.d
        - mysql-student-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=student
        - MYSQL_USER=student
        - MYSQL_PASSWORD=student

    webserver:
      image: nginx:alpine
      container_name: student-webserver
      working_dir: /application
      volumes:
          - ../:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"
      links:
       - php-fpm

    php-fpm:
      build:
        context: .
        args:
            GROUPID: $group
            USERID: $user
        dockerfile: php-fpm/Dockerfile
      env_file: .env
      container_name: student-php-fpm
      working_dir: /application
      volumes:
        - ../:/application
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/phpdbg/conf.d/99-overrides.ini
      links:
        - db

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: student-phpmyadmin
      ports:
        - "8082:80"
      links:
        - db

volumes:
  mysql-student-data:
    external: false