statistic_page:
  path: /
  defaults: { _controller: AppBundle:Default:statistic }
  methods: [GET]

add_battery:
  path: /add-battery
  defaults: { _controller: AppBundle:Default:index }
  methods: [GET, POST]